#!/bin/bash
set -e  # stop immediately if anything fails

echo "Generating config.js from environment variables..."

# Validate that required env vars are set
REQUIRED_VARS=(
  FIREBASE_API_KEY
  FIREBASE_AUTH_DOMAIN
  FIREBASE_PROJECT_ID
  FIREBASE_STORAGE_BUCKET
  FIREBASE_MESSAGING_SENDER_ID
  FIREBASE_APP_ID
  CEO_EMAIL
  ADMIN_HASH_SUPERADMIN
  ADMIN_HASH_SORTER
  ADMIN_HASH_FULL
)

for VAR in "${REQUIRED_VARS[@]}"; do
  if [ -z "${!VAR}" ]; then
    echo "ERROR: Required environment variable $VAR is not set."
    exit 1
  fi
done

cat > config.js << EOF
// Auto-generated by build.sh — do not edit manually.
window.ARKAN_CONFIG = {
  firebaseApiKey:            "${FIREBASE_API_KEY}",
  firebaseAuthDomain:        "${FIREBASE_AUTH_DOMAIN}",
  firebaseProjectId:         "${FIREBASE_PROJECT_ID}",
  firebaseStorageBucket:     "${FIREBASE_STORAGE_BUCKET}",
  firebaseMessagingSenderId: "${FIREBASE_MESSAGING_SENDER_ID}",
  firebaseAppId:             "${FIREBASE_APP_ID}",
  ceoEmail:                  "${CEO_EMAIL}",
  adminPasswords: {
    "${ADMIN_HASH_SUPERADMIN}": "superadmin",
    "${ADMIN_HASH_SORTER}":     "sorter",
    "${ADMIN_HASH_FULL}":       "full",
  },
};
EOF

echo "config.js generated successfully."